github.com:
    users:
        jakub-malhotra:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: jakub-malhotra
